name: Reusable workflow
on:
  workflow_dispatch:
  workflow_call: 
    inputs:
      who-to-greet:
        type: string
        required: true
        default: "World"
    outputs:
      current-time:
        description: "The current time"
        value: ${{  jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.currenttime }}
    steps:
    - name: Greet someone
      run: echo "Hello ${{ inputs.who-to-greet }}"
    - name: time
      run: echo "currenttime=$(date)" >> $GITHUB_OUTPUT
      
        
  
